import { chromium } from 'playwright';
const b = await chromium.launch({ channel: 'chrome' });
const c = await b.newContext({ viewport:{width:1200,height:900}, colorScheme:'dark', deviceScaleFactor:1 });
const p = await c.newPage();
await p.goto('http://localhost:4321/', { waitUntil:'networkidle' });
await p.evaluate(()=>window.scrollTo(0, document.body.scrollHeight));
await p.waitForTimeout(500);
await p.screenshot({ path:'/private/tmp/keres-shots/dark-footer.png' });
console.log('shot taken');
await b.close();
