// Concatenate the five source stylesheets into one public/assets/site.css.
//
// Why: the five <link> tags were loading serially and cost ~1.16s of
// render-blocking time on a throttled mobile connection, which put the
// homepage LCP at 3.0s against a 2.5s budget. The sources stay separate
// for authoring; the browser gets one request.
//
// Cascade order is load-bearing — tokens define every variable the next
// three read, and components.css is last so it can override the legacy
// sheets. Do not reorder.
//
// Runs automatically via the `prebuild` / `predev` npm hooks.

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assets = join(root, 'public', 'assets');

const ORDER = ['fonts.css', 'tokens.css', 'styles.css', 'pages.css', 'components.css'];

const parts = ORDER.map((name) => {
  const css = readFileSync(join(assets, name), 'utf8');
  return `/* ===== ${name} ===== */\n${css}`;
});

const banner = `/* GENERATED FILE — do not edit.
   Built by scripts/build-css.mjs from, in order:
     ${ORDER.join(' → ')}
   Edit those, not this. Runs automatically on npm run build / dev. */\n`;

// esbuild ships with Astro, so minifying costs no new dependency. It
// parses the CSS properly, which a regex minifier does not — the data:
// URI in the select arrow and the content: '→ ' strings both survive.
const { transform } = await import('esbuild');
const joined = parts.join('\n\n');
const { code } = await transform(joined, { loader: 'css', minify: true });
const out = banner + code;
writeFileSync(join(assets, 'site.css'), out);

// Content hash becomes the cache-busting query, so a stale stylesheet is
// impossible and nobody has to remember to bump a version by hand.
const hash = createHash('sha256').update(out).digest('hex').slice(0, 8);
writeFileSync(join(root, 'src', 'data', 'cssHash.ts'),
  `// GENERATED by scripts/build-css.mjs. Do not edit.\nexport const CSS_HASH = '${hash}';\n`);

console.log(`[css] site.css ${(out.length / 1024).toFixed(1)}KB · hash ${hash}`);
